portfolio/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf import settings

from rest_framework import routers

from projects.views import IndexView, ProjectView, AboutView, ContactView, SitemapView, BingView, ProjectViewSet, CategoryViewSet #, UserViewSet
from blog.views import ArticleView, ArticleListView, BlogTagView, BlogCategoryView, BlogIndexView


urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^projects/(?P<slug>[A-Za-z0-9_\-]+)/$', ProjectView.as_view(), name='project'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^sitemap\.xml$', SitemapView.as_view(), name='sitemap'),
    url(r'^BingSiteAuth\.xml$', BingView.as_view(), name='bing'),
    # url(r'^blog/$', BlogIndexView.as_view(), name='article_list'),
    # url(r'^blog/articles/(?P<category_slug>[A-Za-z0-9_\-]+)/(?P<slug>[A-Za-z0-9_\-]+)/$', ArticleView.as_view(), name='article'),
    # url(r'^blog/categories/(?P<slug>[A-Za-z0-9_\-]+)/$', BlogCategoryView.as_view(), name='category'),
    # url(r'^blog/tags/(?P<slug>[A-Za-z0-9_\-]+)/$', BlogTagView.as_view(), name='tag'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
)

router = routers.DefaultRouter()
router.register(r'api/projects', ProjectViewSet)
router.register(r'api/categories', CategoryViewSet)

urlpatterns += router.urls

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Resume redirect from old site's URL to home
urlpatterns += url(r'^kenneth_roraback_resume.pdf$', RedirectView.as_view(url=reverse('home')), name="resume_redirect"),

blog/models.py
from django.db import models
from datetime import date
from django.template.defaultfilters import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=200, db_index=True)
    body = RichTextUploadingField()
    created = models.DateField(auto_now_add=True)
    posted = models.DateField(default=date.today, db_index=True)
    category = models.ForeignKey('BlogCategory')
    tags = models.ManyToManyField('BlogTag')
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    login_required = models.BooleanField(default=False)
    published = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ["posted"]

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

class BlogCategory(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    rank = models.IntegerField(blank=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ["title"]

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BlogCategory, self).save(*args, **kwargs)

class BlogTag(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    rank = models.IntegerField(blank=True)

    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ["title"]

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(BlogTag, self).save(*args, **kwargs)

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView

from blog.models import Article, BlogCategory, BlogTag

# Create your views here.
class ArticleView(DetailView):
    model = Article
    template_name = 'blog/article.html'

class ArticleListView(ListView):
    model = Article
    template_name = 'blog/article_list.html'

class BlogCategoryView(DetailView):
    model = BlogCategory
    template_name = 'blog/category.html'

    # def get_context_data(self, **kwargs):
    #      context = super(BlogCategoryView, self).get_context_data(**kwargs)
    #      context.update({
    #          'articles': Article.objects.filter(article__published=True, article__category=category).order_by('rank')
    #      })
 
class BlogTagView(DetailView):
    model = BlogTag
    template_name = 'blog/tag.html'

class BlogIndexView(ListView):
    queryset = Article.objects.filter(published=True)
    template_name = 'blog/article_list.html'

    def get_context_data(self, **kwargs):
        context = super(BlogIndexView, self).get_context_data(**kwargs)
        context.update({
            'categories': BlogCategory.objects.filter(article__published=True).order_by('rank'),
            'blog_tags': BlogTag.objects.filter(article__published=True).order_by('rank')
        })
        return context     
        

templates/blog/article.html
{% extends "base.html" %}
{% block title %}Kenneth Roraback -> {{ article.title }}{% endblock %}
{% block content %}
	{% block related_posts_block %}
		{% load tags %}
		{% related_posts article %}
	{% endblock %}
<section>
	{{ article.body | safe }}
</section>
{% endblock %}
{% block footer_image %}{% endblock %}

templates/blog/article_list.html
{% extends "blog/base.html" %}
{% block title %}Kenneth Roraback -> Design and Front-end Development {% endblock %}
{% block content %}
	<section class="blog-main">
		<h2>Recent Posts</h2>
		{% for article in article_list %}
			<a href="{% url 'article' article.category.slug article.slug %}">
				<article>
					<h3>{{ article.title }}</h3>
					<p>{{ article.body | striptags | truncatewords:50 }}</p>
				</article>
			</a>
		{% endfor %}
	</section>
{% endblock %}
{% block footer_image %}{% endblock %}

templates/blog/base.html
{% extends "base.html" %}
{% block blog_nav %}
	{% load tags %}
	<nav>
		{% block related_posts_block %}{% endblock %}
		{% blog_categories %}
		{% blog_tags %}
	</nav>
{% endblock %}
{% block footer_image %}{% endblock %}

templates/blog/category.html
{% extends "blog/base.html" %}
{% block title %}Kenneth Roraback -> {{ blogcategory.title }}{% endblock %}
{% block content %}
	<section class="blog-main">
		<h2>{{ blogcategory.title }}</h2>

		{% for article in blogcategory.article_set.all %}
			<a href="{% url 'article' blogcategory.slug article.slug %}">
				<article>
					<h3>{{ article.title }}</h3>
					<p>{{ article.body | striptags | truncatewords:50 }}</p>
				</article>
			</a>
		{% endfor %}
	</section>
{% endblock %}

templates/blog/tag.html
{% extends "blog/base.html" %}
{% block title %}Kenneth Roraback -> {{ blogtag }}{% endblock %}
{% block content %}
	<section class="blog-main">
		<h2>{{ blogtag.title }}</h2>

		{% for article in blogtag.article_set.all %}
			<a href="{% url 'article' blogtag.slug article.slug %}">
				<article>
					<h3>{{ article.title }}</h3>
					<p>{{ article.body | striptags | truncatewords:50 }}</p>
				</article>
			</a>
		{% endfor %}
	</section>
{% endblock %}