portfolio/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf import settings

from rest_framework import routers

from projects.views import IndexView, ProjectView, AboutView, ContactView, SitemapView, BingView, ProjectViewSet, CategoryViewSet #, UserViewSet
from blog.views import ArticleView, ArticleListView, BlogTagView, BlogCategoryView, BlogIndexView


urlpatterns = patterns('',
    url(r'^$', IndexView.as_view(), name='home'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^projects/(?P<slug>[A-Za-z0-9_\-]+)/$', ProjectView.as_view(), name='project'),
    url(r'^about/$', AboutView.as_view(), name='about'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^sitemap\.xml$', SitemapView.as_view(), name='sitemap'),
    url(r'^BingSiteAuth\.xml$', BingView.as_view(), name='bing'),
    # url(r'^blog/$', BlogIndexView.as_view(), name='article_list'),
    # url(r'^blog/articles/(?P<category_slug>[A-Za-z0-9_\-]+)/(?P<slug>[A-Za-z0-9_\-]+)/$', ArticleView.as_view(), name='article'),
    # url(r'^blog/categories/(?P<slug>[A-Za-z0-9_\-]+)/$', BlogCategoryView.as_view(), name='category'),
    # url(r'^blog/tags/(?P<slug>[A-Za-z0-9_\-]+)/$', BlogTagView.as_view(), name='tag'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
)

router = routers.DefaultRouter()
router.register(r'api/projects', ProjectViewSet)
router.register(r'api/categories', CategoryViewSet)

urlpatterns += router.urls

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Resume redirect from old site's URL to home
urlpatterns += url(r'^kenneth_roraback_resume.pdf$', RedirectView.as_view(url=reverse('home')), name="resume_redirect"),

projects/models.py
import math
from django.db import models
from django.template.defaultfilters import slugify

class Image(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="images", default="img/default.jpg")
    thumbnail = models.ImageField(upload_to="images", default="img/defaultThumb.jpg", blank=True, null=True)
    caption = models.TextField()
    rank = models.IntegerField()
    project = models.ForeignKey('Project')
    
    class Meta:
        ordering = ["rank"]

    def __unicode__(self):
        return self.title

class Addendum(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    attachment = models.FileField(upload_to="addenda", blank=True, null=True)
    attachment_description = models.CharField(max_length=100, blank=True, null=True)
    project = models.ForeignKey('Project')
    rank = models.IntegerField()
    
    class Meta:
        verbose_name_plural = "addenda"
        ordering = ["rank"]

    def __unicode__(self):
        return self.title

class Video(models.Model):
    title = models.CharField(max_length=100)
    embed_id = models.CharField(max_length=100)
    caption = models.TextField()
    rank = models.IntegerField()
    project = models.ForeignKey('Project')

    class Meta:
        ordering = ["rank"]

    def __unicode__(self):
        return self.title

class Testimonial(models.Model):
    text = models.TextField()
    by_name = models.CharField(max_length=100)
    by_position = models.CharField(max_length=100)
    by_company = models.CharField(max_length=100)
    rank = models.IntegerField()
 
    class Meta:
        ordering = ["rank"]

    def __unicode__(self):
        return self.by_name

class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    challenges = models.TextField(blank=True, null=True)
    solutions = models.TextField(blank=True, null=True)
    has_video = models.BooleanField(default=True)
    video_embed_code = models.TextField(blank=True, null=True)
    thumbnail = models.ImageField(upload_to="projects", default="img/defaultThumb.jpg", blank=True, null=True)
    main_image = models.ImageField(upload_to="projects", default="img/default.jpg", blank=True, null=True)
    main_caption = models.TextField(blank=True, null=True)
    main_alt_tag = models.CharField(max_length=200)
    category = models.ForeignKey('Category')
    rank = models.IntegerField()
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    login_required = models.BooleanField(default=False)
    secret = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    tagline = models.TextField(blank=True, null=True)
    testimonials = models.ManyToManyField('Testimonial', blank=True, null=True)
    
    class Meta:
        ordering = ["rank"]

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category) + '-' + slugify(self.title)
        super(Project, self).save(*args, **kwargs)

    @property
    def percentageHeight(self):
        iHeight = self.main_image.height
        iWidth = self.main_image.width
        pHeight = 100.00 * iHeight / iWidth
        return pHeight
    
    @property
    def numFigures(self):
        return self.image_set.all().count() + self.video_set.all().count() + 1
    
    @property
    def percentageWidth(self):
        numFigures = self.numFigures
        pWidth = math.floor(100 * 100000 / numFigures)
        pWidth = round(pWidth/100000,5)
        print pWidth
        return pWidth

class Category(models.Model):
    title = models.CharField(max_length=30)
    rank = models.IntegerField()
    
    class Meta:
        verbose_name_plural = "categories"
        ordering = ["rank"]

    def __unicode__(self):
        return self.title

projects/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User, Group
from django.views.generic import ListView, DetailView, TemplateView
from django.http import HttpResponse, HttpResponsePermanentRedirect
from django.core.urlresolvers import reverse

from rest_framework import viewsets, generics

from projects.serializers import UserSerializer, ProjectSerializer, ProjectPreviewSerializer, CategorySerializer
from projects.permissions import ReadOnly
from projects.models import Category, Project

class IndexView(ListView):
    model = Category
    template_name = 'index.html'
    
    # Forward old URLs to correct views
    def dispatch(self, *args, **kwargs):
        if 'section' in self.request.GET:
            section = self.request.GET["section"]
            
            if section == 'about':
                return HttpResponsePermanentRedirect(reverse('about'))
            elif section == 'contact':
                return HttpResponsePermanentRedirect(reverse('contact'))
            else:
                return super(IndexView, self).dispatch(*args, **kwargs)
        elif 'project' in self.request.GET:
            project = self.request.GET["project"]

            if project == 'mfadtsymposium':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=18).slug}))
            elif project == 'globalbillboard':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=17).slug}))
            elif project == 'firstreaders':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=8).slug}))
            elif project == 'learnwithhomer':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=28).slug}))
            elif project == 'opensansschoolbook':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=19).slug}))
            elif project == 'vulnerabilitymapping':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=27).slug}))
            elif project == 'costofhcv':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=24).slug}))
            elif project == 'hrmap':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=10).slug}))
            elif project == 'explodingtwitbird':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=15).slug}))
            elif project == 'tweetstalker':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=25).slug}))
            elif project == 'bigbook':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=6).slug}))
            elif project == 'ehrntemplates':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=11).slug}))
            elif project == 'ehrnstyleguide':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=12).slug}))
            elif project == 'emmanuel':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=14).slug}))
            elif project == 'benpowell':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=3).slug}))
            elif project == '3x3':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=4).slug}))
            elif project == 'bicycle':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=5).slug}))
            elif project == 'psychosis_text':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=22).slug}))
            elif project == 'psychosis_design':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=21).slug}))
            elif project == 'psychosis_direction':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=20).slug}))
            elif project == 'ecity':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=13).slug}))
            elif project == 'readingroom':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=23).slug}))
            elif project == 'designstudio':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=1).slug}))
            elif project == 'wolfgangweingart':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=26).slug}))
            elif project == 'expressivetype':
                return HttpResponsePermanentRedirect(reverse('project', kwargs={'slug':Project.objects.get(pk=16).slug}))
            else:
                return super(IndexView, self).dispatch(*args, **kwargs)
        else:
            return super(IndexView, self).dispatch(*args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['randomPopOrder'] = ('pop-zero', 'pop-one', 'pop-two', 'pop-three', 'pop-four', 'pop-five', 'pop-six', 'pop-seven', 'pop-eight', 'pop-nine', )
        return context

class ProjectView(DetailView):
    model = Project
    template_name = 'project.html'
    
    def post(self, request, **kwargs):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponse("success")
            else:
                return HttpResponse("It Looks like this account is disabled.")
        else:
            return HttpResponse("Your username/password is incorrect. Please try again.")

class AboutView(TemplateView):
    template_name = 'about.html'

class ContactView(TemplateView):
    template_name = 'contact.html'

class SitemapView(ListView):
    model = Project
    template_name ="xml/sitemap.xml"

class BingView(TemplateView):
    template_name = "xml/BingSiteAuth.xml"

# API Views
class ProjectViewSet(viewsets.ModelViewSet):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    permission_classes = (ReadOnly,)
    
    def get_queryset(self):
        # Return all projects if user is logged in. Only return public projects, otherwise.
        if self.request.user and self.request.user.is_authenticated():
             return Project.objects.all()
        else:
            return Project.objects.filter(login_required=False)

class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer
    permission_classes = (ReadOnly,)

templates/base.html
<!DOCTYPE html>
{% load tags %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}Kenneth Roraback -> Design Work{% endblock %}</title>
		<meta name="description" content="{% block description %}Kenneth Roraback's portfolio website: Come and check out projects in web and mobile design, interaction, branding, video, theater and architecture. If you like it, let Kenny know by sending him an e-mail!{% endblock %}">
		<meta name="keywords" content="{% block keywords %}kenneth roraback kenny UX design user experience interactive video theater architecture typography MIT parsons design{% endblock %}" />

        <link rel="stylesheet" href="{{ STATIC_URL }}{% if ENVIRONMENT = 'PRODUCTION' %}prod_{% endif %}stylesheets/main.css">
	    <link rel="shortcut icon" href="{{ STATIC_URL }}img/icons/favicon.ico" />
	    <link rel="apple-touch-icon" href="{{ STATIC_URL }}img/icons/apple-touch-icon.png" />
	    <link rel="apple-touch-icon-precomposed" href="{{ STATIC_URL }}img/icons/apple-touch-icon-precomposed.png"/>
	    <link rel="apple-touch-icon" sizes="72x72" href="{{ STATIC_URL }}img/icons/apple-touch-icon-72x72-precomposed.png" />
	    <link rel="apple-touch-icon" sizes="114x114" href="{{ STATIC_URL }}img/icons/apple-touch-icon-114x114-precomposed.png" />
	    <link rel="apple-touch-icon" sizes= "144x144" href="{{ STATIC_URL }}img/icons/apple-touch-icon-144x144-precomposed.png" />
		<script type="text/javascript" src="https://use.typekit.com/lcf0sfk.js"></script>
		<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
        <script src="{{ STATIC_URL }}js/vendor/modernizr-2.6.2.min.js"></script>
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

		<nav>
			<ul>
			{% with url_name=request.resolver_match.url_name %}
			{% block header_home_link %}
				<li class="siteTitle"><a href="{% url 'home' %}" title="Kenneth Roraback - Design Work" {% if url_name == 'home' or url_name == 'project' %}class="active"{% endif %}><span class="secret">'</span>Kenneth Roraback<span class="secret">'</span><mark>=&gt;</mark><span class="secret">'</span>Design Work<span class="secret">'</span></a></li>
			{% endblock %}
				<li><a href="{% url 'about' %}" title="About Kenneth Roraback" {% if url_name == 'about' %}class="active"{% endif %}><mark>&nbsp;About</mark></a></li>
				<li><a href="{{ STATIC_URL }}pdf/kenneth-roraback-resume.pdf" target="_blank" title="Kenneth Roraback's Resume"><mark>Resum&eacute;</mark></a></li>
				<li><a href="{% url 'contact' %}" title="Contact Kenneth Roraback" {% if url_name == 'contact' %}class="active"{% endif %}><mark>Contact</mark></a></h2></li>
				<li><a href="{% random_project %}" title="random project"><mark>Get lucky!&nbsp;</mark></a></li>
			</ul>
		</nav>
		<main>
{% block blog_nav %}{% endblock %}
{% block content %}{% endblock %}
		</main>
		<footer>
			<nav>
				<ul>
					<li class="siteTitle"><a href="{% url 'home' %}" title="Kenneth Roraback - Design Work" {% if url_name == 'home' or url_name == 'project' %}class="active"{% endif %}><span class="secret">'</span>Kenneth Roraback<span class="secret">'</span><mark>=&gt;</mark><span class="secret">'</span>Design Work<span class="secret">'</span></a></li>
					<li><a href="{% url 'about' %}" title="About Kenneth Roraback" {% if url_name == 'about' %}class="active"{% endif %}><mark>&nbsp;About</mark></a></li>
					<li><a href="{{ STATIC_URL }}pdf/kenneth-roraback-resume.pdf" target="_blank"><mark>Resum&eacute;</mark></a></li>
					<li><a href="{% url 'contact' %}" title="Contact Kenneth Roraback" {% if url_name == 'contact' %}class="active"{% endif %}><mark>Contact</mark></a></li>
					<li><a href="{% random_project %}" title="random project"><mark>Get lucky!&nbsp;</mark></a></li>
				</ul>
			</nav>
			{% endwith %}
		</footer>


        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="{{ STATIC_URL }}js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
        <script src="{{ STATIC_URL }}js/main.js"></script>
		{% block extrascripts %}{% endblock %}
        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-21549573-1');ga('send','pageview');
        </script>
    </body>
</html>

templates/contact.html
{% extends "base.html" %}

{% block title %}Kenneth Roraback - Contact{% endblock %}
{% block description %}Kenneth Roraback: Want to contact me? I love to get feedback about my work in interaction design, film, theater and more!{% endblock %}

{% block content %}
<div id="main" role="main">
	<h2>Don't be shy. Say hello!</h2>
	<div class="slideshow">
		<div class="image-container" style="width: 100%;">
			<figure style="width: 100%;">
				<div class="content-wrapper" style="padding-bottom: 75%;">
					<img src="{{ STATIC_URL }}img/kenny-roraback.jpg" alt="Kenneth Roraback - Screenshot from Learn with Homer" />
				</div>
				<figcaption>A screenshot from the Learn with Homer app for iPad. This is my favorite thinking cap in the app. It&rsquo;s a <em>taco</em> hat that also has its <em>own</em> hat. I think that is AWESOME.</figcaption>
			</figure>
		</div>
	</div>
	<p><span class="secret">'</span>Thank you for visiting the site!<span class="secret">'</span> <mark>=&gt;</mark> <span class="secret">'</span>I hope that you have enjoyed my work. If you have questions or opinions (positive or negative!) about the site or about my work, you are welcome to send me an e-mail. I would love to hear from you!<span class="secret">',</span></p>
	<p><span class="secret">'</span>E-mail<span class="secret">'</span> <mark>=&gt;</mark> <span class="secret">'</span><a href="mailto:kenny@kennethroraback.com">kenny@kennethroraback.com</a><span class="secret">',</span></p>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
	{# <li class="siteTitle"><h1><a href="{% url 'home' %}" title="Kenneth Roraback - Home"><span class="secret">'</span>Kenneth Roraback<span class="secret">'</span><mark>=&gt;</mark><span class="secret">'</span>The Stories I Tell<span class="secret">'</span></a></h1></li> #}

{% block content %}
<header class="index-header">
	<div class="kenny-roraback-photo"><img src="{{ STATIC_URL }}img/kenneth-roraback.png" alt="Kenneth Roraback"></div><!-- 
	--><dl>
		<dt><h1>Who is Kenneth Roraback?</h1></dt>
		<dd>UX/UI Designer with strong analytical and creative problem solving and a deeply cross-functional skill set</dd>
		<dd>Loves to tackle challenging interaction problems and create smooth, simple user flows</dd>
		<dd>Educated at MIT: S.B. Physics + S.B. Theater</dd>
		<dd>Educated at Parsons: M.F.A. Design and Technology</dd>
		<dd>5 years of start-up leadership experience + 4 years of project management at a Fortune 500 company</dd>
	</dl>
</header>
{% for category in category_list %}
	{% if category.project_set.all.count > 0 %}
			<section class="indexSection">
				<h2>{{ category.title }}</h2>
				<ul>
		{% for project in category.project_set.all %}
			{% if user.is_authenticated or not project.secret %}
				{% if project.active or user.is_superuser %}
					<li class="{{ randomPopOrder|random }}">
						<a href="{% url 'project' project.slug %}" title="{{ project.title }}">
							<figure>
								<div class="img-container">
									<img src="{{ project.thumbnail.url }}" alt="{{ project.title }}" />
								</div>
								<figcaption><span class="table-container"><span class="table"><span class="cell">{{ project.title|safe }}</span></span></span></figcaption>
							</figure>
						</a>
					</li>
				{% endif %}
			{% endif %}
		{% endfor %}
	{% endif %}
				</ul>
			</section>
{% endfor %}
{% endblock %}

templates/project.html
{% extends "base.html" %}

{% block title %}Kenneth Roraback - {{ project.category }} - {{ project.title|safe }}{% endblock %}
{% if not project.login_required %}
	{% block description %}Project: {{ project.description }}{% endblock %}
{% endif %}
{% block content %}
{% autoescape off %}
	<header>	
		<h1 class="project-page">{{ project.title }}</h1>
	{% if project.tagline %}	
		<h2 class="project-tagline">{{ project.tagline }}</h2>
	{% endif %}
	</header>
	{% if project.login_required and not user.is_authenticated %}
		<p style="margin-top:.5em;">You&rsquo;ll need to enter a username and password to view this project. Don&rsquo;t have one? Send me a note!</p>
		<div class="errors">hjkdsjlksjfklsjfklf</div>
		<form method="post" action="." name="loginForm" id="loginForm">
		{% csrf_token %}
			<label for="username">Username:</label>
			<input id="username" name="username" type="text"  />
			<label for="password">Password:</label>
			<input id="password" name="password" type="password" />
			<input type="submit" value="Log in" />
			<input type="hidden" name="next" value="." />
		</form>
	{% else %}
		<div class="slideshow{% if project.percentageHeight > 100 %} vertical-layout{% endif %}">
			<div class="image-container" style="width:{% widthratio project.numFigures 1 100 %}%;">
				<figure style="width: {{ project.percentageWidth }}%;">
				{% if project.has_video %}
					<div class="content-wrapper" style="padding-bottom: {{ project.percentageHeight }}%;">
						<iframe src="//player.vimeo.com/video/{{ project.video_embed_code }}" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
					</div>
					<figcaption>{{ project.main_caption }}</figcaption>
				{% else %}
					<div class="content-wrapper" style="padding-bottom: {{ project.percentageHeight }}%;">
						<img src="{{ project.main_image.url }}" alt="{{ project.main_alt_tag }}" />
					</div>
					<figcaption>{{ project.main_caption }}</figcaption>
				{% endif %}
				</figure>
		{% for video in project.video_set.all %}
				<figure style="width: {{ project.percentageWidth }}%;">
					<div class="content-wrapper" style="padding-bottom: {{ project.percentageHeight }}%;">
						<iframe src="//player.vimeo.com/video/{{ video.embed_id }}" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
					</div>
					<figcaption>{{ video.caption }}</figcaption>
				</figure>
		{% endfor %}
		{% for image in project.image_set.all %}
				<figure style="width: {{ project.percentageWidth }}%;">
					<div class="content-wrapper" style="padding-bottom: {{ project.percentageHeight }}%;">
						<img src="{{ image.image.url }}" alt="{{ image.title }}" />
					</div>
					<figcaption>{{ image.caption }}</figcaption>
				</figure>
		{% endfor %}
			</div>
			<div class="left-bar"></div>
			<div class="right-bar"></div>
		</div>
		<p><span class="secret">'</span>Project<span class="secret">'</span> <mark>=&gt;</mark> <span class="secret">'</span>{{ project.description }}<span class="secret">',</span></p>
		<p><span class="secret">'</span>Challenges<span class="secret">'</span> <mark>=&gt;</mark> <span class="secret">'</span>{{ project.challenges }}<span class="secret">',</span></p>
		{% if project.solutions != "" %}
		<p><span class="secret">'</span>Solutions<span class="secret">'</span> <mark>=&gt;</mark> <span class="secret">'</span>{{ project.solutions }}<span class="secret">'</span></p>
		{% endif %}
	{% for addendum in project.addendum_set.all %}
		<p><span class="secret">'</span>{{ addendum.title }}<span class="secret">'</span> <mark>=&gt;</mark> <span class="secret">'</span> {% if addendum.attachment %}<a href="{{ addendum.attachment.url }}" target="_blank">{{ addendum.attachment_description }}:</a>{% endif %} {{ addendum.description }}<span class="secret">',</span>
	{% endfor %}
{% endif %}
		&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<mark>)<span class="secret">;</span></mark></p>
	<script>
		var percentageHeight = {{ project.percentageHeight }};
	</script>
{% endautoescape %}
{% endblock %}

{% block extrascripts %}
<script>
</script>
{% endblock %}